server:
  error:
    include-message: always

spring:
  profiles:
    active:
      - LOCAL
  datasource:
    url: jdbc:postgresql://172.17.0.1/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  application:
    name: shop
  data:
    redis:
      host: 172.17.0.1
      port: 6379

  rabbitmq:
    host: 172.17.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        submitOrder-out-0:
          destination: submitOrder-in-0
        updateOrderStatus-out-0:
          destination: updateOrderStatus-in-0

  jpa:
    hibernate:
      ddl-auto: update

redis:
  ttl: PT30h

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
